[framework]
name = "http.jl"

[main]
urls.plaintext = "/plaintext"
urls.json = "/json"
approach = "Realistic"
classification = "None"
os = "Linux"
orm = "None"
platform = "None"
webserver = "HTTP.jl"
versus = ""
