[framework]
name = "wsgi"

[main]
urls.plaintext = "/plaintext"
urls.json = "/json"
approach = "Stripped"
classification = "Platform"
database_os = "Linux"
os = "Linux"
orm = "Raw"
platform = "None"
webserver = "Meinheld"
versus = "wsgi"
