[framework]
name = "servicetalk"

[main]
urls.plaintext = "/plaintext"
urls.json = "/json"
approach = "Realistic"
classification = "Micro"
os = "Linux"
orm = "Raw"
platform = "servicetalk"
webserver = "None"
versus = ""
