[framework]
name = "bayou"

[main]
urls.plaintext = "/plaintext"
urls.json = "/json"
approach = "Realistic"
classification = "Platform"
os = "Linux"
orm = "Raw"
platform = "Bayou"
webserver = "None"
versus = ""
