[framework]
name = "revel"

[main]
urls.plaintext = "/plaintext"
urls.json = "/json"
approach = "Realistic"
classification = "Fullstack"
database = "MySQL"
database_os = "Linux"
os = "Linux"
orm = "Raw"
platform = "None"
webserver = "None"
versus = "go"
tags = ["broken"]

[raw]
urls.db = "/db"
urls.query = "/db?queries="
urls.update = "/update?queries="
urls.fortune = "/fortune"
approach = "Realistic"
classification = "Fullstack"
database = "MySQL"
database_os = "Linux"
os = "Linux"
orm = "Raw"
platform = "None"
webserver = "None"
versus = "go"
tags = ["broken"]

[qbs]
urls.db = "/qbs-db"
urls.query = "/qbs-db?queries="
urls.update = "/qbs-update?queries="
urls.fortune = "/qbs-fortune"
approach = "Realistic"
classification = "Fullstack"
database = "MySQL"
database_os = "Linux"
os = "Linux"
orm = "micro"
platform = "None"
webserver = "None"
versus = "go"
tags = ["broken"]

[jet]
urls.db = "/jet-db"
urls.query = "/jet-db?queries="
urls.update = "/jet-update?queries="
urls.fortune = "/jet-fortune"
approach = "Realistic"
classification = "Fullstack"
database = "MySQL"
database_os = "Linux"
os = "Linux"
orm = "micro"
platform = "None"
webserver = "None"
versus = "go"
tags = ["broken"]

[fast]
urls.plaintext = "/plaintext"
urls.json = "/json"
approach = "Realistic"
classification = "Fullstack"
database = "MySQL"
database_os = "Linux"
os = "Linux"
orm = "Raw"
platform = "None"
webserver = "None"
versus = "go"
tags = ["broken"]
