[framework]
name = "chicagoboss"

[main]
urls.plaintext = "/plaintext"
urls.json = "/json"
approach = "Realistic"
classification = "Fullstack"
os = "Linux"
orm = "raw"
platform = "Cowboy"
webserver = "None"
versus = ""
