[framework]
name = "nginx"

[main]
urls.plaintext = "/plaintext"
approach = "Realistic"
classification = "Platform"
database_os = "Linux"
os = "Linux"
orm = "Raw"
platform = "None"
webserver = "nginx"
versus = ""
