[framework]
name = "aspnetcore-corert"

[main]
urls.plaintext = "/plaintext"
urls.json = "/json"
approach = "Stripped"
classification = "Platform"
os = "Linux"
orm = "Raw"
platform = ".NET"
webserver = "Kestrel"
versus = "aspcore"
