[framework]
name = "blaze"

[main]
urls.plaintext = "/plaintext"
urls.json = "/json"
approach = "Realistic"
classification = "Micro"
os = "Linux"
orm = "Raw"
platform = "blaze"
webserver = "None"
versus = "None"
