[framework]
name = "h2o_mruby"

[main]
urls.plaintext = "/plaintext"
urls.json = "/json"
approach = "Realistic"
classification = "Platform"
os = "Linux"
orm = "Raw"
platform = "None"
webserver = "h2o"
versus = "None"
