[framework]
name = "activej"

[main]
urls.plaintext = "/plaintext"
urls.json = "/json"
approach = "Realistic"
classification = "Micro"
database_os = "Linux"
os = "Linux"
orm = "None"
platform = "activej"
webserver = "None"
versus = ""
