[framework]
name = "falcon"

[main]
urls.json = "/json"
urls.db = "/db"
urls.query = "/queries/"
urls.update = "/updates/"
urls.fortune = "/fortunes"
urls.plaintext = "/plaintext"
approach = "Realistic"
classification = "Micro"
database = "Postgres"
orm = "Full"
platform = "WSGI"
webserver = "Meinheld"
os = "Linux"
database_os = "Linux"
versus = "wsgi"

[bjoern]
urls.json = "/json"
urls.db = "/db"
urls.query = "/queries/"
urls.update = "/updates/"
urls.fortune = "/fortunes"
urls.plaintext = "/plaintext"
approach = "Realistic"
classification = "Micro"
database = "Postgres"
orm = "Full"
platform = "WSGI"
webserver = "bjoern"
os = "Linux"
database_os = "Linux"
versus = "wsgi"

[waitress]
urls.json = "/json"
urls.db = "/db"
urls.query = "/queries/"
urls.update = "/updates/"
urls.fortune = "/fortunes"
urls.plaintext = "/plaintext"
approach = "Realistic"
classification = "Micro"
database = "Postgres"
orm = "Full"
platform = "WSGI"
webserver = "waitress"
os = "Linux"
database_os = "Linux"
versus = "wsgi"

[orjson]
urls.json = "/json"
urls.db = "/db"
urls.query = "/queries/"
urls.update = "/updates/"
urls.fortune = "/fortunes"
urls.plaintext = "/plaintext"
approach = "Realistic"
classification = "Micro"
database = "Postgres"
orm = "Full"
platform = "WSGI"
webserver = "Meinheld"
os = "Linux"
database_os = "Linux"
versus = "wsgi"

[pypy3]
urls.json = "/json"
urls.db = "/db"
urls.query = "/queries/"
urls.update = "/updates/"
urls.fortune = "/fortunes"
urls.plaintext = "/plaintext"
approach = "Realistic"
classification = "Micro"
database = "Postgres"
orm = "Full"
platform = "WSGI"
webserver = "Gunicorn"
os = "Linux"
database_os = "Linux"
versus = "wsgi"
