[framework]
name = "servlet3"

[main]
urls.plaintext = "/plaintext"
urls.json = "/json"
approach = "Realistic"
classification = "Platform"
os = "Linux"
orm = "Raw"
platform = "Servlet"
webserver = "Tomcat"
versus = "servlet"

[sync]
urls.plaintext = "/plaintext"
urls.json = "/json"
approach = "Realistic"
classification = "Platform"
os = "Linux"
orm = "Raw"
platform = "Servlet"
webserver = "Tomcat"
versus = "servlet"
