[framework]
name = "lwan"

[main]
urls.plaintext = "/plaintext"
urls.json = "/json"
urls.db = "/db"
urls.query = "/queries?queries="
urls.fortune = "/fortunes"
urls.cached_query = "/cached-queries?count="
approach = "Realistic"
classification = "Micro"
database = "mysql"
database_os = "Linux"
os = "Linux"
orm = "Raw"
platform = "Lwan"
webserver = "Lwan"
versus = "None"
tags = ["broken"] # 2022-02-17 - msmith - it did not build

[lua]
urls.plaintext = "/lua.plaintext"
urls.json = "/lua.json"
approach = "Realistic"
classification = "Micro"
database = "mysql"
database_os = "Linux"
os = "Linux"
orm = "Raw"
platform = "Lwan"
webserver = "Lwan"
versus = "None"
tags = ["broken"] # 2022-02-17 - msmith - it did not build
