[framework]
name = "swift-nio"

[main]
urls.plaintext = "/p"
urls.json = "/j"
approach = "Realistic"
classification = "Platform"
os = "Linux"
orm = "Raw"
platform = "None"
webserver = "None"
versus = ""
