[framework]
name = "uwsgi"

[main]
urls.json = "/json"
approach = "Stripped"
classification = "Platform"
database_os = "Linux"
os = "Linux"
orm = "Raw"
platform = "None"
webserver = "uWSGI"
versus = ""

[nginx-uwsgi]
urls.json = "/json"
approach = "Stripped"
classification = "Platform"
database_os = "Linux"
os = "Linux"
orm = "Raw"
platform = "None"
webserver = "nginx-uWSGI"
versus = ""
