[framework]
name = "octane"

[main]
urls.plaintext = "/plaintext"
urls.json = "/json"
approach = "Stripped"
classification = "Platform"
database_os = "Linux"
os = "Linux"
orm = "Raw"
platform = "None"
webserver = "None"
versus = "octane"
tags = ["broken"] # 2022-02-18 - msmith - failed to build
