[framework]
name = "javalin"

[main]
urls.plaintext = "/plaintext"
urls.json = "/json"
approach = "Stripped"
classification = "Platform"
os = "Linux"
orm = "Raw"
platform = "Servlet"
webserver = "None"
versus = ""
