[framework]
name = "m-web-server"

[main]
urls.plaintext = "/plaintext"
urls.json = "/json"
approach = "Realistic"
classification = "Fullstack"
os = "Linux"
orm = "None"
platform = "None"
webserver = "m-web-server"
versus = ""
