[framework]
name = "hug"

[main]
urls.plaintext = "/plaintext"
approach = "Realistic"
classification = "Micro"
database_os = "Linux"
os = "Linux"
orm = "Raw"
platform = "Falcon"
webserver = "None"
versus = "wsgi"
