[framework]
name = "jersey"

[main]
urls.plaintext = "/plaintext"
approach = "Realistic"
classification = "Fullstack"
os = "Linux"
orm = "Micro"
platform = "Servlet"
webserver = "Resin"
versus = "servlet"
