[framework]
name = "snunit"

[main]
urls.plaintext = "/plaintext"
urls.json = "/json"
approach = "Realistic"
classification = "Micro"
database_os = "Linux"
os = "Linux"
orm = "None"
platform = "Unit Nginx"
webserver = "None"
versus = ""
