[framework]
name = "finagle"

[main]
urls.plaintext = "/plaintext"
urls.json = "/json"
approach = "Realistic"
classification = "Micro"
os = "Linux"
orm = "Raw"
platform = "Netty"
webserver = "None"
versus = "netty"
