[framework]
name = "curacao"

[main]
urls.plaintext = "/plaintext"
urls.json = "/json"
approach = "Realistic"
classification = "Micro"
os = "Linux"
orm = "Raw"
platform = "Servlet"
webserver = "None"
versus = "servlet"
