[framework]
name = "httpaf"

[main]
urls.plaintext = "/plaintext"
urls.json = "/json"
approach = "Realistic"
classification = "Platform"
database_os = "Linux"
os = "Linux"
orm = "None"
platform = "httpaf"
webserver = "None"
versus = "None"
