[framework]
name = "collie"

[main]
urls.plaintext = "/plaintext"
urls.json = "/json"
approach = "Realistic"
classification = "Platform"
os = "Linux"
orm = "Raw"
platform = "Collie"
webserver = "None"
versus = "Collie"

[ldc]
urls.plaintext = "/plaintext"
urls.json = "/json"
approach = "Realistic"
classification = "Platform"
os = "Linux"
orm = "Raw"
platform = "Collie"
webserver = "None"
versus = "Collie"
