[framework]
name = "jetty"

[main]
urls.plaintext = "/plaintext"
urls.json = "/json"
approach = "Realistic"
classification = "Platform"
database_os = "Linux"
os = "Linux"
orm = "Raw"
platform = "Jetty"
webserver = "None"
versus = "servlet"

[servlet]
urls.plaintext = "/plaintext"
urls.json = "/json"
approach = "Realistic"
classification = "Platform"
database_os = "Linux"
os = "Linux"
orm = "Raw"
platform = "Jetty"
webserver = "None"
versus = "servlet"
