[framework]
name = "embedio"

[main]
urls.plaintext = "/plaintext"
urls.json = "/json"
approach = "Realistic"
classification = "Fullstack"
os = "Linux"
orm = "Raw"
platform = ".NET"
webserver = "EmbedIO"
versus = "None"
