[framework]
name = "baratine"

[main]
urls.plaintext = "/plaintext"
urls.json = "/json"
approach = "Stripped"
classification = "Platform"
os = "Linux"
orm = "Raw"
platform = "Baratine"
webserver = "None"
versus = "baratine"
