[framework]
name = "evhttp-sharp"

[main]
urls.plaintext = "/plaintext"
urls.json = "/"
approach = "Realistic"
classification = "Micro"
os = "Linux"
orm = "Raw"
platform = "None"
webserver = "None"
versus = "evhttp-sharp"
